version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build:
      context: ./app1
    ports:
      - 8001:8000

  app2:
    build:
      context: ./app2
    ports:
      - 8002:8000

  app3:
    build:
      context: ./app3
    ports:
      - 8003:8000